spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/notecup?characterEncoding=UTF-8
    username: root
    password: 1111
  jpa:
    generate-ddl: true
server:
  port: 80