spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/notecup?characterEncoding=UTF-8
    username: root
    password: 1111
  messages:
    basename: messages/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
   
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
   
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 80
  
 